# Generated by Django 4.2.23 on 2025-09-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subjectgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject_group', 'school_class')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
    ]
