# Generated by Django 4.2.23 on 2025-09-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
        ('grades', '0002_alter_grade_unique_together_grade_subject_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'school_class')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject_group',
        ),
    ]
