# Generated by Django 4.2.23 on 2025-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_academicyear_examtype_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
