# Generated by Django 4.2.23 on 2025-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_academicyear_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='academic_year_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
