# Generated by Django 4.2.23 on 2025-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_examtype_academic_year_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
