# Generated by Django 4.2.23 on 2025-09-06 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('grades', '0005_alter_grade_unique_together_grade_exam_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='روزهای حاضر')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='روزهای غایب')),
                ('sick_days', models.PositiveIntegerField(default=0, verbose_name='روزهای مریض')),
                ('leave_days', models.PositiveIntegerField(default=0, verbose_name='روزهای رخصت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='grades.examtype')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attendance_created', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendance', to='classes.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendance', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'exam_type', 'school_class')},
            },
        ),
    ]
